import {
  Activity,
  AppWindow,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Blocks,
  Calendar,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleQuestionMark,
  ClipboardPaste,
  Clock,
  Cloud,
  Copy,
  CornerLeftUp,
  Cpu,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode,
  FileText,
  Folder,
  FolderOpen,
  Funnel,
  Globe,
  Grid3x3,
  HardDrive,
  Hexagon,
  History,
  Image,
  Info,
  Key,
  KeyRound,
  Layers,
  Link2,
  Loader,
  Lock,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Package,
  PanelRight,
  PanelsTopLeft,
  Pencil,
  Play,
  Plug,
  PlugZap,
  Plus,
  Power,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Scan,
  Scissors,
  Search,
  Server,
  Settings2,
  Shield,
  Square,
  SquareCheckBig,
  Terminal,
  Trash,
  TriangleAlert,
  Upload,
  User,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-vue-next'

/**
 * The finite icon registry is the only place that imports Lucide components.
 * Call sites keep concise kebab-case names while the bundler can tree-shake the
 * thousands of icons the application never renders.
 */
const iconMap = {
  activity: Activity,
  'alert-triangle': TriangleAlert,
  'app-window': AppWindow,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  blocks: Blocks,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-question-mark': CircleQuestionMark,
  'clipboard-paste': ClipboardPaste,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  'corner-left-up': CornerLeftUp,
  cpu: Cpu,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-code-2': FileCode,
  'file-text': FileText,
  filter: Funnel,
  folder: Folder,
  'folder-open': FolderOpen,
  globe: Globe,
  grid: Grid3x3,
  'hard-drive': HardDrive,
  hexagon: Hexagon,
  history: History,
  image: Image,
  info: Info,
  key: Key,
  'key-round': KeyRound,
  layers: Layers,
  'link-2': Link2,
  loader: Loader,
  lock: Lock,
  'log-out': LogOut,
  maximize: Maximize2,
  menu: Menu,
  minimize: Minimize2,
  'more-horizontal': Ellipsis,
  package: Package,
  'panel-right': PanelRight,
  'panels-top-left': PanelsTopLeft,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  'plug-zap': PlugZap,
  plus: Plus,
  power: Power,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  server: Server,
  'settings-2': Settings2,
  shield: Shield,
  'square-check': SquareCheckBig,
  stop: Square,
  terminal: Terminal,
  trash: Trash,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  user: User,
  users: Users,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>

type IconName = keyof typeof iconMap

export function iconFor(name: string): LucideIcon {
  return iconMap[name as IconName] ?? iconMap['circle-question-mark']
}
