d /etc/nexa-panel 0750 root nexa -
d /etc/containers/systemd 0755 root root -
d /var/lib/nexa-panel 0750 nexa nexa -
d /var/lib/postgresql/nexa-backups 0750 postgres postgres -
d /var/lib/nexa-panel/backups 0750 root nexa -
d /var/lib/nexa-panel/backups/mysql 0750 root nexa -
d /etc/nexa-panel/admin-tools 0750 root nexa -
d /etc/nexa-panel/admin-tools/phpmyadmin 0750 root root -
d /etc/nexa-panel/admin-tools/phpmyadmin/sessions 0750 root root -
d /etc/nexa-panel/admin-tools/pgadmin 0750 root root -
d /etc/nexa-panel/admin-tools/pgadmin/data 0750 root root -
d /var/log/nexa-panel 0750 nexa nexa -
d /srv/nexa 0755 root root -
d /srv/nexa/acme 0755 root root -
d /srv/nexa/acme/.well-known 0755 root root -
d /srv/nexa/acme/.well-known/acme-challenge 0755 root root -
d /srv/nexa/sites 0755 root root -
