d /run/nexa-panel 2750 nexa nexa -
d /etc/nexa-panel 0711 root root -
z /etc/nexa-panel/agent.token 0600 root root -
d /etc/containers/systemd 0755 root root -
d /var/lib/nexa-panel 0700 nexa nexa -
z /var/lib/nexa-panel/control.db* 0600 nexa nexa -
d /var/lib/postgresql/nexa-backups 0750 postgres postgres -
d /var/lib/nexa-panel/backups 0750 nexa nexa -
d /var/lib/nexa-panel/backups/mysql 0750 nexa nexa -
d /etc/nexa-panel/admin-tools 0700 root root -
d /etc/nexa-panel/admin-tools/phpmyadmin 0750 root 33 -
d /etc/nexa-panel/admin-tools/phpmyadmin/sessions 0750 33 33 -
d /etc/nexa-panel/admin-tools/pgadmin 0750 root 5050 -
d /etc/nexa-panel/admin-tools/pgadmin/data 0700 5050 5050 -
d /etc/nexa-panel/generated 0711 root root -
d /etc/nexa-panel/generated/tasks 0711 root root -
d /var/log/nexa-panel 0700 nexa nexa -
d /srv/nexa 0755 root root -
d /srv/nexa/acme 0755 root root -
d /srv/nexa/acme/.well-known 0755 root root -
d /srv/nexa/acme/.well-known/acme-challenge 0755 root root -
d /srv/nexa/sites 0755 root root -
