// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CertificateStatus.
const (
	CertificateStatusActive    CertificateStatus = "active"
	CertificateStatusFailed    CertificateStatus = "failed"
	CertificateStatusIssuing   CertificateStatus = "issuing"
	CertificateStatusPlanReady CertificateStatus = "plan_ready"
	CertificateStatusPlanning  CertificateStatus = "planning"
	CertificateStatusRenewing  CertificateStatus = "renewing"
	CertificateStatusRevoked   CertificateStatus = "revoked"
	CertificateStatusRevoking  CertificateStatus = "revoking"
)

// Valid indicates whether the value is a known member of the CertificateStatus enum.
func (e CertificateStatus) Valid() bool {
	switch e {
	case CertificateStatusActive:
		return true
	case CertificateStatusFailed:
		return true
	case CertificateStatusIssuing:
		return true
	case CertificateStatusPlanReady:
		return true
	case CertificateStatusPlanning:
		return true
	case CertificateStatusRenewing:
		return true
	case CertificateStatusRevoked:
		return true
	case CertificateStatusRevoking:
		return true
	default:
		return false
	}
}

// Defines values for ChangePhpExtensionAction.
const (
	ChangePhpExtensionActionInstall ChangePhpExtensionAction = "install"
	ChangePhpExtensionActionRemove  ChangePhpExtensionAction = "remove"
)

// Valid indicates whether the value is a known member of the ChangePhpExtensionAction enum.
func (e ChangePhpExtensionAction) Valid() bool {
	switch e {
	case ChangePhpExtensionActionInstall:
		return true
	case ChangePhpExtensionActionRemove:
		return true
	default:
		return false
	}
}

// Defines values for CreateDomainKind.
const (
	CreateDomainKindAlias     CreateDomainKind = "alias"
	CreateDomainKindRedirect  CreateDomainKind = "redirect"
	CreateDomainKindSubdomain CreateDomainKind = "subdomain"
)

// Valid indicates whether the value is a known member of the CreateDomainKind enum.
func (e CreateDomainKind) Valid() bool {
	switch e {
	case CreateDomainKindAlias:
		return true
	case CreateDomainKindRedirect:
		return true
	case CreateDomainKindSubdomain:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseAccess.
const (
	Connect   DatabaseAccess = "connect"
	ReadOnly  DatabaseAccess = "read_only"
	ReadWrite DatabaseAccess = "read_write"
)

// Valid indicates whether the value is a known member of the DatabaseAccess enum.
func (e DatabaseAccess) Valid() bool {
	switch e {
	case Connect:
		return true
	case ReadOnly:
		return true
	case ReadWrite:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseEngine.
const (
	DatabaseEngineMysql      DatabaseEngine = "mysql"
	DatabaseEnginePostgresql DatabaseEngine = "postgresql"
)

// Valid indicates whether the value is a known member of the DatabaseEngine enum.
func (e DatabaseEngine) Valid() bool {
	switch e {
	case DatabaseEngineMysql:
		return true
	case DatabaseEnginePostgresql:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseServerKind.
const (
	DatabaseServerKindMariadb    DatabaseServerKind = "mariadb"
	DatabaseServerKindMysql      DatabaseServerKind = "mysql"
	DatabaseServerKindPostgresql DatabaseServerKind = "postgresql"
)

// Valid indicates whether the value is a known member of the DatabaseServerKind enum.
func (e DatabaseServerKind) Valid() bool {
	switch e {
	case DatabaseServerKindMariadb:
		return true
	case DatabaseServerKindMysql:
		return true
	case DatabaseServerKindPostgresql:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatus.
const (
	DatabaseStatusActive    DatabaseStatus = "active"
	DatabaseStatusApplying  DatabaseStatus = "applying"
	DatabaseStatusBackingUp DatabaseStatus = "backing_up"
	DatabaseStatusDown      DatabaseStatus = "down"
	DatabaseStatusFailed    DatabaseStatus = "failed"
	DatabaseStatusOnline    DatabaseStatus = "online"
	DatabaseStatusPlanReady DatabaseStatus = "plan_ready"
	DatabaseStatusPlanning  DatabaseStatus = "planning"
	DatabaseStatusRestoring DatabaseStatus = "restoring"
	DatabaseStatusVerified  DatabaseStatus = "verified"
)

// Valid indicates whether the value is a known member of the DatabaseStatus enum.
func (e DatabaseStatus) Valid() bool {
	switch e {
	case DatabaseStatusActive:
		return true
	case DatabaseStatusApplying:
		return true
	case DatabaseStatusBackingUp:
		return true
	case DatabaseStatusDown:
		return true
	case DatabaseStatusFailed:
		return true
	case DatabaseStatusOnline:
		return true
	case DatabaseStatusPlanReady:
		return true
	case DatabaseStatusPlanning:
		return true
	case DatabaseStatusRestoring:
		return true
	case DatabaseStatusVerified:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentModeChangeMode.
const (
	DeploymentModeChangeModeDeployer DeploymentModeChangeMode = "deployer"
	DeploymentModeChangeModeStandard DeploymentModeChangeMode = "standard"
)

// Valid indicates whether the value is a known member of the DeploymentModeChangeMode enum.
func (e DeploymentModeChangeMode) Valid() bool {
	switch e {
	case DeploymentModeChangeModeDeployer:
		return true
	case DeploymentModeChangeModeStandard:
		return true
	default:
		return false
	}
}

// Defines values for DomainKind.
const (
	DomainKindAlias     DomainKind = "alias"
	DomainKindPrimary   DomainKind = "primary"
	DomainKindRedirect  DomainKind = "redirect"
	DomainKindSubdomain DomainKind = "subdomain"
)

// Valid indicates whether the value is a known member of the DomainKind enum.
func (e DomainKind) Valid() bool {
	switch e {
	case DomainKindAlias:
		return true
	case DomainKindPrimary:
		return true
	case DomainKindRedirect:
		return true
	case DomainKindSubdomain:
		return true
	default:
		return false
	}
}

// Defines values for DomainStatus.
const (
	DomainStatusActivating DomainStatus = "activating"
	DomainStatusActive     DomainStatus = "active"
	DomainStatusFailed     DomainStatus = "failed"
	DomainStatusPlanReady  DomainStatus = "plan_ready"
	DomainStatusPlanning   DomainStatus = "planning"
)

// Valid indicates whether the value is a known member of the DomainStatus enum.
func (e DomainStatus) Valid() bool {
	switch e {
	case DomainStatusActivating:
		return true
	case DomainStatusActive:
		return true
	case DomainStatusFailed:
		return true
	case DomainStatusPlanReady:
		return true
	case DomainStatusPlanning:
		return true
	default:
		return false
	}
}

// Defines values for FileEntryKind.
const (
	Dir     FileEntryKind = "dir"
	File    FileEntryKind = "file"
	Other   FileEntryKind = "other"
	Symlink FileEntryKind = "symlink"
)

// Valid indicates whether the value is a known member of the FileEntryKind enum.
func (e FileEntryKind) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	case Other:
		return true
	case Symlink:
		return true
	default:
		return false
	}
}

// Defines values for JobState.
const (
	JobStateFailed    JobState = "failed"
	JobStateQueued    JobState = "queued"
	JobStateRunning   JobState = "running"
	JobStateSucceeded JobState = "succeeded"
)

// Valid indicates whether the value is a known member of the JobState enum.
func (e JobState) Valid() bool {
	switch e {
	case JobStateFailed:
		return true
	case JobStateQueued:
		return true
	case JobStateRunning:
		return true
	case JobStateSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for LivenessStatus.
const (
	Ok LivenessStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessStatus enum.
func (e LivenessStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MFADisableResponseMfaEnabled.
const (
	False MFADisableResponseMfaEnabled = false
)

// Valid indicates whether the value is a known member of the MFADisableResponseMfaEnabled enum.
func (e MFADisableResponseMfaEnabled) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for ManagedRole.
const (
	ManagedRoleAdmin     ManagedRole = "admin"
	ManagedRoleDeveloper ManagedRole = "developer"
	ManagedRoleOperator  ManagedRole = "operator"
	ManagedRoleViewer    ManagedRole = "viewer"
)

// Valid indicates whether the value is a known member of the ManagedRole enum.
func (e ManagedRole) Valid() bool {
	switch e {
	case ManagedRoleAdmin:
		return true
	case ManagedRoleDeveloper:
		return true
	case ManagedRoleOperator:
		return true
	case ManagedRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for MemorySnapshotProfile.
const (
	MemorySnapshotProfileCompact     MemorySnapshotProfile = "compact"
	MemorySnapshotProfilePro         MemorySnapshotProfile = "pro"
	MemorySnapshotProfileStandard    MemorySnapshotProfile = "standard"
	MemorySnapshotProfileUnsupported MemorySnapshotProfile = "unsupported"
)

// Valid indicates whether the value is a known member of the MemorySnapshotProfile enum.
func (e MemorySnapshotProfile) Valid() bool {
	switch e {
	case MemorySnapshotProfileCompact:
		return true
	case MemorySnapshotProfilePro:
		return true
	case MemorySnapshotProfileStandard:
		return true
	case MemorySnapshotProfileUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for NodePlanAction.
const (
	NodePlanActionCreate NodePlanAction = "create"
	NodePlanActionNone   NodePlanAction = "none"
	NodePlanActionRemove NodePlanAction = "remove"
	NodePlanActionUpdate NodePlanAction = "update"
)

// Valid indicates whether the value is a known member of the NodePlanAction enum.
func (e NodePlanAction) Valid() bool {
	switch e {
	case NodePlanActionCreate:
		return true
	case NodePlanActionNone:
		return true
	case NodePlanActionRemove:
		return true
	case NodePlanActionUpdate:
		return true
	default:
		return false
	}
}

// Defines values for NodePlanKind.
const (
	NexaProbeV1 NodePlanKind = "nexa.probe.v1"
)

// Valid indicates whether the value is a known member of the NodePlanKind enum.
func (e NodePlanKind) Valid() bool {
	switch e {
	case NexaProbeV1:
		return true
	default:
		return false
	}
}

// Defines values for PasswordResponseNext.
const (
	Authenticated PasswordResponseNext = "authenticated"
	MfaChallenge  PasswordResponseNext = "mfa_challenge"
	MfaEnrollment PasswordResponseNext = "mfa_enrollment"
)

// Valid indicates whether the value is a known member of the PasswordResponseNext enum.
func (e PasswordResponseNext) Valid() bool {
	switch e {
	case Authenticated:
		return true
	case MfaChallenge:
		return true
	case MfaEnrollment:
		return true
	default:
		return false
	}
}

// Defines values for PhpDirectiveAccess.
const (
	PHPINIALL    PhpDirectiveAccess = "PHP_INI_ALL"
	PHPININONE   PhpDirectiveAccess = "PHP_INI_NONE"
	PHPINIPERDIR PhpDirectiveAccess = "PHP_INI_PERDIR"
	PHPINISYSTEM PhpDirectiveAccess = "PHP_INI_SYSTEM"
	PHPINIUSER   PhpDirectiveAccess = "PHP_INI_USER"
)

// Valid indicates whether the value is a known member of the PhpDirectiveAccess enum.
func (e PhpDirectiveAccess) Valid() bool {
	switch e {
	case PHPINIALL:
		return true
	case PHPININONE:
		return true
	case PHPINIPERDIR:
		return true
	case PHPINISYSTEM:
		return true
	case PHPINIUSER:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready ReadinessStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeEngine.
const (
	Php RuntimeEngine = "php"
)

// Valid indicates whether the value is a known member of the RuntimeEngine enum.
func (e RuntimeEngine) Valid() bool {
	switch e {
	case Php:
		return true
	default:
		return false
	}
}

// Defines values for SchedulePlanKind.
const (
	NexaScheduleChangeV1 SchedulePlanKind = "nexa.schedule.change.v1"
)

// Valid indicates whether the value is a known member of the SchedulePlanKind enum.
func (e SchedulePlanKind) Valid() bool {
	switch e {
	case NexaScheduleChangeV1:
		return true
	default:
		return false
	}
}

// Defines values for ScheduledTaskStatus.
const (
	ScheduledTaskStatusActivating  ScheduledTaskStatus = "activating"
	ScheduledTaskStatusActive      ScheduledTaskStatus = "active"
	ScheduledTaskStatusDraft       ScheduledTaskStatus = "draft"
	ScheduledTaskStatusFailed      ScheduledTaskStatus = "failed"
	ScheduledTaskStatusPlanReady   ScheduledTaskStatus = "plan_ready"
	ScheduledTaskStatusPlanning    ScheduledTaskStatus = "planning"
	ScheduledTaskStatusRolledBack  ScheduledTaskStatus = "rolled_back"
	ScheduledTaskStatusRollingBack ScheduledTaskStatus = "rolling_back"
)

// Valid indicates whether the value is a known member of the ScheduledTaskStatus enum.
func (e ScheduledTaskStatus) Valid() bool {
	switch e {
	case ScheduledTaskStatusActivating:
		return true
	case ScheduledTaskStatusActive:
		return true
	case ScheduledTaskStatusDraft:
		return true
	case ScheduledTaskStatusFailed:
		return true
	case ScheduledTaskStatusPlanReady:
		return true
	case ScheduledTaskStatusPlanning:
		return true
	case ScheduledTaskStatusRolledBack:
		return true
	case ScheduledTaskStatusRollingBack:
		return true
	default:
		return false
	}
}

// Defines values for SetDeploymentModeMode.
const (
	SetDeploymentModeModeDeployer SetDeploymentModeMode = "deployer"
	SetDeploymentModeModeStandard SetDeploymentModeMode = "standard"
)

// Valid indicates whether the value is a known member of the SetDeploymentModeMode enum.
func (e SetDeploymentModeMode) Valid() bool {
	switch e {
	case SetDeploymentModeModeDeployer:
		return true
	case SetDeploymentModeModeStandard:
		return true
	default:
		return false
	}
}

// Defines values for SiteDeploymentMode.
const (
	SiteDeploymentModeDeployer SiteDeploymentMode = "deployer"
	SiteDeploymentModeStandard SiteDeploymentMode = "standard"
)

// Valid indicates whether the value is a known member of the SiteDeploymentMode enum.
func (e SiteDeploymentMode) Valid() bool {
	switch e {
	case SiteDeploymentModeDeployer:
		return true
	case SiteDeploymentModeStandard:
		return true
	default:
		return false
	}
}

// Defines values for SiteStatus.
const (
	SiteStatusActivating  SiteStatus = "activating"
	SiteStatusActive      SiteStatus = "active"
	SiteStatusDeleting    SiteStatus = "deleting"
	SiteStatusDraft       SiteStatus = "draft"
	SiteStatusFailed      SiteStatus = "failed"
	SiteStatusPlanReady   SiteStatus = "plan_ready"
	SiteStatusPlanning    SiteStatus = "planning"
	SiteStatusRolledBack  SiteStatus = "rolled_back"
	SiteStatusRollingBack SiteStatus = "rolling_back"
)

// Valid indicates whether the value is a known member of the SiteStatus enum.
func (e SiteStatus) Valid() bool {
	switch e {
	case SiteStatusActivating:
		return true
	case SiteStatusActive:
		return true
	case SiteStatusDeleting:
		return true
	case SiteStatusDraft:
		return true
	case SiteStatusFailed:
		return true
	case SiteStatusPlanReady:
		return true
	case SiteStatusPlanning:
		return true
	case SiteStatusRolledBack:
		return true
	case SiteStatusRollingBack:
		return true
	default:
		return false
	}
}

// Defines values for SiteArtifactKind.
const (
	Logrotate      SiteArtifactKind = "logrotate"
	NginxHtpasswd  SiteArtifactKind = "nginx-htpasswd"
	NginxRatelimit SiteArtifactKind = "nginx-ratelimit"
	NginxSite      SiteArtifactKind = "nginx-site"
	PhpFpmPool     SiteArtifactKind = "php-fpm-pool"
	SiteRoot       SiteArtifactKind = "site-root"
)

// Valid indicates whether the value is a known member of the SiteArtifactKind enum.
func (e SiteArtifactKind) Valid() bool {
	switch e {
	case Logrotate:
		return true
	case NginxHtpasswd:
		return true
	case NginxRatelimit:
		return true
	case NginxSite:
		return true
	case PhpFpmPool:
		return true
	case SiteRoot:
		return true
	default:
		return false
	}
}

// Defines values for SiteLogRotationFrequency.
const (
	Daily  SiteLogRotationFrequency = "daily"
	Hourly SiteLogRotationFrequency = "hourly"
	Weekly SiteLogRotationFrequency = "weekly"
)

// Valid indicates whether the value is a known member of the SiteLogRotationFrequency enum.
func (e SiteLogRotationFrequency) Valid() bool {
	switch e {
	case Daily:
		return true
	case Hourly:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// Defines values for SitePlanKind.
const (
	NexaSiteActivationV1 SitePlanKind = "nexa.site.activation.v1"
)

// Valid indicates whether the value is a known member of the SitePlanKind enum.
func (e SitePlanKind) Valid() bool {
	switch e {
	case NexaSiteActivationV1:
		return true
	default:
		return false
	}
}

// Defines values for SiteRouteKind.
const (
	SiteRouteKindAlias     SiteRouteKind = "alias"
	SiteRouteKindRedirect  SiteRouteKind = "redirect"
	SiteRouteKindSubdomain SiteRouteKind = "subdomain"
)

// Valid indicates whether the value is a known member of the SiteRouteKind enum.
func (e SiteRouteKind) Valid() bool {
	switch e {
	case SiteRouteKindAlias:
		return true
	case SiteRouteKindRedirect:
		return true
	case SiteRouteKindSubdomain:
		return true
	default:
		return false
	}
}

// Defines values for SiteSettingsCharset.
const (
	Big5        SiteSettingsCharset = "big5"
	Empty       SiteSettingsCharset = ""
	EucJp       SiteSettingsCharset = "euc-jp"
	EucKr       SiteSettingsCharset = "euc-kr"
	Gb2312      SiteSettingsCharset = "gb2312"
	Iso88591    SiteSettingsCharset = "iso-8859-1"
	Iso885915   SiteSettingsCharset = "iso-8859-15"
	Iso88592    SiteSettingsCharset = "iso-8859-2"
	Koi8R       SiteSettingsCharset = "koi8-r"
	Koi8U       SiteSettingsCharset = "koi8-u"
	Off         SiteSettingsCharset = "off"
	ShiftJis    SiteSettingsCharset = "shift_jis"
	Utf8        SiteSettingsCharset = "utf-8"
	Windows1251 SiteSettingsCharset = "windows-1251"
	Windows1252 SiteSettingsCharset = "windows-1252"
)

// Valid indicates whether the value is a known member of the SiteSettingsCharset enum.
func (e SiteSettingsCharset) Valid() bool {
	switch e {
	case Big5:
		return true
	case Empty:
		return true
	case EucJp:
		return true
	case EucKr:
		return true
	case Gb2312:
		return true
	case Iso88591:
		return true
	case Iso885915:
		return true
	case Iso88592:
		return true
	case Koi8R:
		return true
	case Koi8U:
		return true
	case Off:
		return true
	case ShiftJis:
		return true
	case Utf8:
		return true
	case Windows1251:
		return true
	case Windows1252:
		return true
	default:
		return false
	}
}

// Defines values for SiteSettingsPmMode.
const (
	Dynamic  SiteSettingsPmMode = "dynamic"
	Ondemand SiteSettingsPmMode = "ondemand"
	Static   SiteSettingsPmMode = "static"
)

// Valid indicates whether the value is a known member of the SiteSettingsPmMode enum.
func (e SiteSettingsPmMode) Valid() bool {
	switch e {
	case Dynamic:
		return true
	case Ondemand:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleDeveloper UserRole = "developer"
	UserRoleOperator  UserRole = "operator"
	UserRoleViewer    UserRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleDeveloper:
		return true
	case UserRoleOperator:
		return true
	case UserRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for ApplyAdminToolPlanParamsKind.
const (
	ApplyAdminToolPlanParamsKindPgadmin    ApplyAdminToolPlanParamsKind = "pgadmin"
	ApplyAdminToolPlanParamsKindPhpmyadmin ApplyAdminToolPlanParamsKind = "phpmyadmin"
)

// Valid indicates whether the value is a known member of the ApplyAdminToolPlanParamsKind enum.
func (e ApplyAdminToolPlanParamsKind) Valid() bool {
	switch e {
	case ApplyAdminToolPlanParamsKindPgadmin:
		return true
	case ApplyAdminToolPlanParamsKindPhpmyadmin:
		return true
	default:
		return false
	}
}

// Defines values for CreateAdminToolLaunchParamsKind.
const (
	CreateAdminToolLaunchParamsKindPgadmin    CreateAdminToolLaunchParamsKind = "pgadmin"
	CreateAdminToolLaunchParamsKindPhpmyadmin CreateAdminToolLaunchParamsKind = "phpmyadmin"
)

// Valid indicates whether the value is a known member of the CreateAdminToolLaunchParamsKind enum.
func (e CreateAdminToolLaunchParamsKind) Valid() bool {
	switch e {
	case CreateAdminToolLaunchParamsKindPgadmin:
		return true
	case CreateAdminToolLaunchParamsKindPhpmyadmin:
		return true
	default:
		return false
	}
}

// Defines values for CreateAdminToolLaunchJSONBodySourceEngine.
const (
	CreateAdminToolLaunchJSONBodySourceEngineMysql      CreateAdminToolLaunchJSONBodySourceEngine = "mysql"
	CreateAdminToolLaunchJSONBodySourceEnginePostgresql CreateAdminToolLaunchJSONBodySourceEngine = "postgresql"
)

// Valid indicates whether the value is a known member of the CreateAdminToolLaunchJSONBodySourceEngine enum.
func (e CreateAdminToolLaunchJSONBodySourceEngine) Valid() bool {
	switch e {
	case CreateAdminToolLaunchJSONBodySourceEngineMysql:
		return true
	case CreateAdminToolLaunchJSONBodySourceEnginePostgresql:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminToolPlanParamsKind.
const (
	GetAdminToolPlanParamsKindPgadmin    GetAdminToolPlanParamsKind = "pgadmin"
	GetAdminToolPlanParamsKindPhpmyadmin GetAdminToolPlanParamsKind = "phpmyadmin"
)

// Valid indicates whether the value is a known member of the GetAdminToolPlanParamsKind enum.
func (e GetAdminToolPlanParamsKind) Valid() bool {
	switch e {
	case GetAdminToolPlanParamsKindPgadmin:
		return true
	case GetAdminToolPlanParamsKindPhpmyadmin:
		return true
	default:
		return false
	}
}

// Defines values for PrepareAdminToolChangeParamsKind.
const (
	PrepareAdminToolChangeParamsKindPgadmin    PrepareAdminToolChangeParamsKind = "pgadmin"
	PrepareAdminToolChangeParamsKindPhpmyadmin PrepareAdminToolChangeParamsKind = "phpmyadmin"
)

// Valid indicates whether the value is a known member of the PrepareAdminToolChangeParamsKind enum.
func (e PrepareAdminToolChangeParamsKind) Valid() bool {
	switch e {
	case PrepareAdminToolChangeParamsKindPgadmin:
		return true
	case PrepareAdminToolChangeParamsKindPhpmyadmin:
		return true
	default:
		return false
	}
}

// Defines values for PrepareAdminToolChangeJSONBodyAction.
const (
	ToolDeploy PrepareAdminToolChangeJSONBodyAction = "tool.deploy"
	ToolStart  PrepareAdminToolChangeJSONBodyAction = "tool.start"
	ToolStop   PrepareAdminToolChangeJSONBodyAction = "tool.stop"
)

// Valid indicates whether the value is a known member of the PrepareAdminToolChangeJSONBodyAction enum.
func (e PrepareAdminToolChangeJSONBodyAction) Valid() bool {
	switch e {
	case ToolDeploy:
		return true
	case ToolStart:
		return true
	case ToolStop:
		return true
	default:
		return false
	}
}

// Defines values for PrepareApplicationChangeJSONBodyAction.
const (
	PackageInstall PrepareApplicationChangeJSONBodyAction = "package.install"
	PackageRemove  PrepareApplicationChangeJSONBodyAction = "package.remove"
)

// Valid indicates whether the value is a known member of the PrepareApplicationChangeJSONBodyAction enum.
func (e PrepareApplicationChangeJSONBodyAction) Valid() bool {
	switch e {
	case PackageInstall:
		return true
	case PackageRemove:
		return true
	default:
		return false
	}
}

// Defines values for PreviewBackupRestore200JSONResponseBodyIntegrityState.
const (
	PreviewBackupRestore200JSONResponseBodyIntegrityStateFailed     PreviewBackupRestore200JSONResponseBodyIntegrityState = "failed"
	PreviewBackupRestore200JSONResponseBodyIntegrityStatePassed     PreviewBackupRestore200JSONResponseBodyIntegrityState = "passed"
	PreviewBackupRestore200JSONResponseBodyIntegrityStateUnverified PreviewBackupRestore200JSONResponseBodyIntegrityState = "unverified"
)

// Valid indicates whether the value is a known member of the PreviewBackupRestore200JSONResponseBodyIntegrityState enum.
func (e PreviewBackupRestore200JSONResponseBodyIntegrityState) Valid() bool {
	switch e {
	case PreviewBackupRestore200JSONResponseBodyIntegrityStateFailed:
		return true
	case PreviewBackupRestore200JSONResponseBodyIntegrityStatePassed:
		return true
	case PreviewBackupRestore200JSONResponseBodyIntegrityStateUnverified:
		return true
	default:
		return false
	}
}

// Defines values for PreviewBackupRestore200JSONResponseBodyItemsKind.
const (
	PreviewBackupRestore200JSONResponseBodyItemsKindDatabase PreviewBackupRestore200JSONResponseBodyItemsKind = "database"
	PreviewBackupRestore200JSONResponseBodyItemsKindSite     PreviewBackupRestore200JSONResponseBodyItemsKind = "site"
)

// Valid indicates whether the value is a known member of the PreviewBackupRestore200JSONResponseBodyItemsKind enum.
func (e PreviewBackupRestore200JSONResponseBodyItemsKind) Valid() bool {
	switch e {
	case PreviewBackupRestore200JSONResponseBodyItemsKindDatabase:
		return true
	case PreviewBackupRestore200JSONResponseBodyItemsKindSite:
		return true
	default:
		return false
	}
}

// Defines values for PrepareCertificateOperationJSONBodyOperation.
const (
	Issue  PrepareCertificateOperationJSONBodyOperation = "issue"
	Renew  PrepareCertificateOperationJSONBodyOperation = "renew"
	Revoke PrepareCertificateOperationJSONBodyOperation = "revoke"
)

// Valid indicates whether the value is a known member of the PrepareCertificateOperationJSONBodyOperation enum.
func (e PrepareCertificateOperationJSONBodyOperation) Valid() bool {
	switch e {
	case Issue:
		return true
	case Renew:
		return true
	case Revoke:
		return true
	default:
		return false
	}
}

// Defines values for DeleteSiteFile200JSONResponseBodyStatus.
const (
	Deleted DeleteSiteFile200JSONResponseBodyStatus = "deleted"
)

// Valid indicates whether the value is a known member of the DeleteSiteFile200JSONResponseBodyStatus enum.
func (e DeleteSiteFile200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Deleted:
		return true
	default:
		return false
	}
}

// Defines values for AbortSiteFileUpload200JSONResponseBodyStatus.
const (
	Aborted AbortSiteFileUpload200JSONResponseBodyStatus = "aborted"
)

// Valid indicates whether the value is a known member of the AbortSiteFileUpload200JSONResponseBodyStatus enum.
func (e AbortSiteFileUpload200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Aborted:
		return true
	default:
		return false
	}
}

// Defines values for UploadSiteFileChunk200JSONResponseBodyStatus.
const (
	Received UploadSiteFileChunk200JSONResponseBodyStatus = "received"
)

// Valid indicates whether the value is a known member of the UploadSiteFileChunk200JSONResponseBodyStatus enum.
func (e UploadSiteFileChunk200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Received:
		return true
	default:
		return false
	}
}

// AddSshKey defines model for AddSshKey.
type AddSshKey struct {
	Label string `json:"label"`

	// PublicKey One OpenSSH public key line
	PublicKey string `json:"publicKey"`
}

// ApplySystemUpdate defines model for ApplySystemUpdate.
type ApplySystemUpdate struct {
	// Version Target release version; empty installs the latest.
	Version *string `json:"version,omitempty"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action        string                 `json:"action"`
	ActorUserId   *string                `json:"actorUserId,omitempty"`
	Id            int64                  `json:"id"`
	Metadata      map[string]interface{} `json:"metadata"`
	OccurredAt    time.Time              `json:"occurredAt"`
	RemoteAddress *string                `json:"remoteAddress,omitempty"`
	Subject       string                 `json:"subject"`
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	BootstrapToken *string `json:"bootstrapToken,omitempty"`
	Password       string  `json:"password"`
	Username       string  `json:"username"`
}

// Certificate defines model for Certificate.
type Certificate struct {
	CertificatePath *string             `json:"certificatePath,omitempty"`
	CreatedAt       time.Time           `json:"createdAt"`
	Domains         []string            `json:"domains"`
	Email           openapi_types.Email `json:"email"`
	ExpiresAt       *time.Time          `json:"expiresAt,omitempty"`
	ExpiringSoon    bool                `json:"expiringSoon"`
	Failure         *string             `json:"failure,omitempty"`
	Id              string              `json:"id"`
	IssuedAt        *time.Time          `json:"issuedAt,omitempty"`
	LastJobId       *int64              `json:"lastJobId,omitempty"`
	PrimaryDomain   string              `json:"primaryDomain"`
	SiteId          string              `json:"siteId"`
	Status          CertificateStatus   `json:"status"`
	UpdatedAt       time.Time           `json:"updatedAt"`
}

// CertificateStatus defines model for Certificate.Status.
type CertificateStatus string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// ChangePhpExtension defines model for ChangePhpExtension.
type ChangePhpExtension struct {
	Action    ChangePhpExtensionAction `json:"action"`
	Extension string                   `json:"extension"`
	Version   string                   `json:"version"`
}

// ChangePhpExtensionAction defines model for ChangePhpExtension.Action.
type ChangePhpExtensionAction string

// CreateCertificate defines model for CreateCertificate.
type CreateCertificate struct {
	Email  openapi_types.Email `json:"email"`
	SiteId string              `json:"siteId"`
}

// CreateDatabaseGrant defines model for CreateDatabaseGrant.
type CreateDatabaseGrant struct {
	Access     DatabaseAccess `json:"access"`
	DatabaseId string         `json:"databaseId"`
	UserId     string         `json:"userId"`
}

// CreateDatabaseServer Provision a new server instance on an engine that supports it (PostgreSQL today; the MySQL-family engine is discovered, not provisioned).
type CreateDatabaseServer struct {
	Cluster *string `json:"cluster,omitempty"`

	// Engine Engine family a server or resource belongs to.
	Engine  DatabaseEngine `json:"engine"`
	Port    *int           `json:"port,omitempty"`
	Version string         `json:"version"`
}

// CreateDatabaseUser defines model for CreateDatabaseUser.
type CreateDatabaseUser struct {
	// Host Client host scope; MySQL-family servers only.
	Host *string `json:"host,omitempty"`
	Name string  `json:"name"`

	// Password Chosen or generated in the client and applied to the engine as-is; the panel stores only its ciphertext and digest.
	Password string `json:"password"`
	ServerId string `json:"serverId"`
}

// CreateDomain defines model for CreateDomain.
type CreateDomain struct {
	Hostname       string           `json:"hostname"`
	Kind           CreateDomainKind `json:"kind"`
	RedirectTarget *string          `json:"redirectTarget,omitempty"`
	SiteId         string           `json:"siteId"`
}

// CreateDomainKind defines model for CreateDomain.Kind.
type CreateDomainKind string

// CreateManagedDatabase defines model for CreateManagedDatabase.
type CreateManagedDatabase struct {
	Name        string `json:"name"`
	OwnerUserId string `json:"ownerUserId"`
	ServerId    string `json:"serverId"`

	// SiteId Optional site this database belongs to; site teardown blocks on the relation.
	SiteId *string `json:"siteId,omitempty"`
}

// CreateSite defines model for CreateSite.
type CreateSite struct {
	DisplayName   string `json:"displayName"`
	PhpVersion    string `json:"phpVersion"`
	PrimaryDomain string `json:"primaryDomain"`
	Slug          string `json:"slug"`
}

// CreateUser defines model for CreateUser.
type CreateUser struct {
	Password string      `json:"password"`
	Role     ManagedRole `json:"role"`
	Username string      `json:"username"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// DatabaseAccess defines model for DatabaseAccess.
type DatabaseAccess string

// DatabaseEngine Engine family a server or resource belongs to.
type DatabaseEngine string

// DatabaseGrant defines model for DatabaseGrant.
type DatabaseGrant struct {
	Access     DatabaseAccess `json:"access"`
	DatabaseId string         `json:"databaseId"`

	// Engine Engine family a server or resource belongs to.
	Engine    DatabaseEngine `json:"engine"`
	Failure   *string        `json:"failure,omitempty"`
	Id        string         `json:"id"`
	LastJobId *int64         `json:"lastJobId,omitempty"`
	Status    DatabaseStatus `json:"status"`
	UserId    string         `json:"userId"`
}

// DatabaseRestorePoint defines model for DatabaseRestorePoint.
type DatabaseRestorePoint struct {
	DatabaseId string `json:"databaseId"`

	// Engine Engine family a server or resource belongs to.
	Engine     DatabaseEngine `json:"engine"`
	Failure    *string        `json:"failure,omitempty"`
	Id         string         `json:"id"`
	LastJobId  *int64         `json:"lastJobId,omitempty"`
	Sha256     *string        `json:"sha256,omitempty"`
	SizeBytes  *int64         `json:"sizeBytes,omitempty"`
	Status     DatabaseStatus `json:"status"`
	VerifiedAt *time.Time     `json:"verifiedAt,omitempty"`
}

// DatabaseServer One database server on the node — the discovered MySQL-family engine or a PostgreSQL instance.
type DatabaseServer struct {
	Cluster *string `json:"cluster,omitempty"`

	// Engine Engine family a server or resource belongs to.
	Engine  DatabaseEngine `json:"engine"`
	Failure *string        `json:"failure,omitempty"`
	Id      string         `json:"id"`

	// Kind Concrete flavor of the server.
	Kind          DatabaseServerKind `json:"kind"`
	LastJobId     *int64             `json:"lastJobId,omitempty"`
	ManagedByNexa *bool              `json:"managedByNexa,omitempty"`
	Port          int                `json:"port"`
	SocketPath    string             `json:"socketPath"`
	Status        DatabaseStatus     `json:"status"`
	SystemdUnit   string             `json:"systemdUnit"`
	Version       string             `json:"version"`
	VersionText   *string            `json:"versionText,omitempty"`
}

// DatabaseServerKind Concrete flavor of the server.
type DatabaseServerKind string

// DatabaseStatus defines model for DatabaseStatus.
type DatabaseStatus string

// DatabaseUser defines model for DatabaseUser.
type DatabaseUser struct {
	CredentialVersion int `json:"credentialVersion"`

	// Engine Engine family a server or resource belongs to.
	Engine    DatabaseEngine `json:"engine"`
	Failure   *string        `json:"failure,omitempty"`
	Host      *string        `json:"host,omitempty"`
	Id        string         `json:"id"`
	LastJobId *int64         `json:"lastJobId,omitempty"`
	Name      string         `json:"name"`
	ServerId  string         `json:"serverId"`
	Status    DatabaseStatus `json:"status"`
}

// DeployKey The site's Git deploy key. The pair is minted on the node and only the public half ever reaches the control plane, so `present` rather than a non-empty publicKey is what says a key exists.
type DeployKey struct {
	Algorithm   *string    `json:"algorithm,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Fingerprint *string    `json:"fingerprint,omitempty"`

	// KeyVersion Incremented on every rotation
	KeyVersion   int        `json:"keyVersion"`
	LastTestOk   *bool      `json:"lastTestOk,omitempty"`
	LastTestedAt *time.Time `json:"lastTestedAt,omitempty"`
	Present      bool       `json:"present"`

	// PublicKey The public half, ready to register as a repository deploy key
	PublicKey *string `json:"publicKey,omitempty"`

	// Repository The SSH remote this site deploys from, e.g. git@github.com:owner/name.git
	Repository string `json:"repository"`
	SiteId     string `json:"siteId"`
}

// DeploymentModeChange A job is present whenever the site was live enough to need re-applying; without one the mode is stored and the site's next plan picks it up.
type DeploymentModeChange struct {
	Job    *Job                     `json:"job,omitempty"`
	Mode   DeploymentModeChangeMode `json:"mode"`
	SiteId string                   `json:"siteId"`
}

// DeploymentModeChangeMode defines model for DeploymentModeChange.Mode.
type DeploymentModeChangeMode string

// Domain defines model for Domain.
type Domain struct {
	CreatedAt         time.Time    `json:"createdAt"`
	Failure           *string      `json:"failure,omitempty"`
	Hostname          string       `json:"hostname"`
	Id                string       `json:"id"`
	Kind              DomainKind   `json:"kind"`
	LastJobId         *int64       `json:"lastJobId,omitempty"`
	RedirectTarget    *string      `json:"redirectTarget,omitempty"`
	ResolvedAddresses []string     `json:"resolvedAddresses"`
	SiteId            string       `json:"siteId"`
	Status            DomainStatus `json:"status"`
	UpdatedAt         time.Time    `json:"updatedAt"`
}

// DomainKind defines model for Domain.Kind.
type DomainKind string

// DomainStatus defines model for Domain.Status.
type DomainStatus string

// EnsureDeployKey defines model for EnsureDeployKey.
type EnsureDeployKey struct {
	// Repository The SSH remote; empty keeps whatever the panel already stored
	Repository *string `json:"repository,omitempty"`

	// Rotate Replace the pair itself, invalidating the key the repository already trusts
	Rotate *bool `json:"rotate,omitempty"`
}

// Error Shared error envelope returned by every non-2xx JSON response.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`

	// Offset Present on upload offset conflicts; the next byte offset the server expects.
	Offset *int64 `json:"offset,omitempty"`
}

// FileCopyResult defines model for FileCopyResult.
type FileCopyResult struct {
	Bytes   int64 `json:"bytes"`
	Copied  int   `json:"copied"`
	Skipped int   `json:"skipped"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	Group      string        `json:"group"`
	Kind       FileEntryKind `json:"kind"`
	Mode       string        `json:"mode"`
	ModifiedAt time.Time     `json:"modifiedAt"`
	Name       string        `json:"name"`
	Owner      string        `json:"owner"`
	Size       int64         `json:"size"`
}

// FileEntryKind defines model for FileEntry.Kind.
type FileEntryKind string

// FileListing defines model for FileListing.
type FileListing struct {
	Entries   []FileEntry `json:"entries"`
	Truncated bool        `json:"truncated"`
}

// FileReadResult defines model for FileReadResult.
type FileReadResult struct {
	Binary    bool   `json:"binary"`
	Content   string `json:"content"`
	Etag      string `json:"etag"`
	Size      int64  `json:"size"`
	Truncated bool   `json:"truncated"`
}

// FileUpload defines model for FileUpload.
type FileUpload struct {
	UploadId string `json:"uploadId"`
}

// FileWriteResult defines model for FileWriteResult.
type FileWriteResult struct {
	Etag string `json:"etag"`
}

// GenerateSshKey defines model for GenerateSshKey.
type GenerateSshKey struct {
	Label string `json:"label"`
}

// GeneratedSshKey The one and only response carrying a private key. It is generated for the caller, never stored, and cannot be retrieved again.
type GeneratedSshKey struct {
	// Access Interactive SSH access for one site, delivered through that site's Unix Owner. The key bodies are never returned; the fingerprint is the identity a human compares.
	Access     SshAccess `json:"access"`
	Key        SshKey    `json:"key"`
	PrivateKey string    `json:"privateKey"`
}

// IdentityStatus defines model for IdentityStatus.
type IdentityStatus struct {
	Authenticated     bool `json:"authenticated"`
	BootstrapRequired bool `json:"bootstrapRequired"`

	// BootstrapTokenRequired Whether a remote bootstrap request must include the server-issued bootstrap token.
	BootstrapTokenRequired *bool `json:"bootstrapTokenRequired,omitempty"`

	// MfaChallengeRequired Whether the enrolled account must answer its second-factor challenge before the session is authenticated. This is never skippable.
	MfaChallengeRequired bool `json:"mfaChallengeRequired"`

	// MfaEnabled Whether the current session's account has a confirmed second factor.
	MfaEnabled bool `json:"mfaEnabled"`

	// MfaEnrollmentRecommended Whether the authenticated account has no second factor and could add one. Enrollment is optional for every role, including admin, so this is a recommendation the client may surface but must never block on.
	MfaEnrollmentRecommended bool `json:"mfaEnrollmentRecommended"`

	// PasswordPolicy The set-time password policy the server enforces, published so sign-up and password-change forms can render exactly the same requirements. The denylist itself is never exposed, only the fact that one is applied.
	PasswordPolicy PasswordPolicy `json:"passwordPolicy"`
	User           *User          `json:"user,omitempty"`
}

// Job defines model for Job.
type Job struct {
	ActorUserId *string `json:"actorUserId,omitempty"`

	// Attempt Number of worker leases claimed for this job.
	Attempt     int        `json:"attempt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	Failure     *string    `json:"failure,omitempty"`
	Id          int64      `json:"id"`
	Kind        string     `json:"kind"`
	Progress    int        `json:"progress"`

	// Request Kind-specific JSON payload; it may be an object, array, scalar, or null. Credential-shaped fields (password, secret, token, key, passphrase, and similar) are replaced with the string "[redacted]" on the response path.
	Request interface{} `json:"request"`

	// Result Kind-specific JSON result; it may be an object, array, scalar, or null. Redacted the same way as request.
	Result interface{} `json:"result,omitempty"`

	// SiteIds Site scope used to enforce developer grants; omitted for unscoped jobs.
	SiteIds   *[]string  `json:"siteIds,omitempty"`
	StartedAt *time.Time `json:"startedAt,omitempty"`
	State     JobState   `json:"state"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// JobState defines model for Job.State.
type JobState string

// Liveness defines model for Liveness.
type Liveness struct {
	Status  LivenessStatus `json:"status"`
	Version string         `json:"version"`
}

// LivenessStatus defines model for Liveness.Status.
type LivenessStatus string

// LogFile defines model for LogFile.
type LogFile struct {
	ModifiedAt time.Time `json:"modifiedAt"`
	Name       string    `json:"name"`
	Size       int64     `json:"size"`
}

// LogReadResult defines model for LogReadResult.
type LogReadResult struct {
	Lines      []string `json:"lines"`
	NextOffset int64    `json:"nextOffset"`
	Rotated    bool     `json:"rotated"`
	Size       int64    `json:"size"`
	Truncated  bool     `json:"truncated"`
}

// MFAConfirmation defines model for MFAConfirmation.
type MFAConfirmation struct {
	RecoveryCodes []string `json:"recoveryCodes"`
	User          User     `json:"user"`
}

// MFADisableRequest defines model for MFADisableRequest.
type MFADisableRequest struct {
	Password string `json:"password"`
}

// MFADisableResponse defines model for MFADisableResponse.
type MFADisableResponse struct {
	MfaEnabled MFADisableResponseMfaEnabled `json:"mfaEnabled"`
	User       User                         `json:"user"`
}

// MFADisableResponseMfaEnabled defines model for MFADisableResponse.MfaEnabled.
type MFADisableResponseMfaEnabled bool

// MFAEnrollment defines model for MFAEnrollment.
type MFAEnrollment struct {
	ProvisioningUri string `json:"provisioningUri"`
	Secret          string `json:"secret"`
}

// ManagedDatabase defines model for ManagedDatabase.
type ManagedDatabase struct {
	// Engine Engine family a server or resource belongs to.
	Engine         DatabaseEngine `json:"engine"`
	Failure        *string        `json:"failure,omitempty"`
	Id             string         `json:"id"`
	LastJobId      *int64         `json:"lastJobId,omitempty"`
	Name           string         `json:"name"`
	OwnerUserId    string         `json:"ownerUserId"`
	ServerId       string         `json:"serverId"`
	SiteId         *string        `json:"siteId,omitempty"`
	SizeBytes      *int64         `json:"sizeBytes,omitempty"`
	SizeObservedAt *time.Time     `json:"sizeObservedAt,omitempty"`
	Status         DatabaseStatus `json:"status"`
}

// ManagedRole defines model for ManagedRole.
type ManagedRole string

// ManagedUser defines model for ManagedUser.
type ManagedUser struct {
	CreatedAt    time.Time   `json:"createdAt"`
	Id           string      `json:"id"`
	LastLoginAt  *time.Time  `json:"lastLoginAt,omitempty"`
	MfaConfirmed bool        `json:"mfaConfirmed"`
	Role         ManagedRole `json:"role"`

	// SiteIds Sites granted to a developer; empty for unscoped roles.
	SiteIds  []string `json:"siteIds"`
	Username string   `json:"username"`
}

// MemorySnapshot defines model for MemorySnapshot.
type MemorySnapshot struct {
	AvailableBytes int64                 `json:"availableBytes"`
	Profile        MemorySnapshotProfile `json:"profile"`
	Supported      bool                  `json:"supported"`
	SwapFreeBytes  int64                 `json:"swapFreeBytes"`
	SwapTotalBytes int64                 `json:"swapTotalBytes"`
	TotalBytes     int64                 `json:"totalBytes"`
	UsedPercent    float32               `json:"usedPercent"`
}

// MemorySnapshotProfile defines model for MemorySnapshot.Profile.
type MemorySnapshotProfile string

// ModuleDescriptor defines model for ModuleDescriptor.
type ModuleDescriptor struct {
	Dependencies         []string `json:"dependencies"`
	Description          string   `json:"description"`
	EstimatedIdleBytes   int64    `json:"estimatedIdleBytes"`
	Id                   string   `json:"id"`
	Name                 string   `json:"name"`
	RequiredCapabilities []string `json:"requiredCapabilities"`
	Version              string   `json:"version"`
}

// NodePlan defines model for NodePlan.
type NodePlan struct {
	Action    NodePlanAction `json:"action"`
	Before    NodeSnapshot   `json:"before"`
	Changed   bool           `json:"changed"`
	Desired   NodeSnapshot   `json:"desired"`
	ExpiresAt time.Time      `json:"expiresAt"`
	Id        string         `json:"id"`
	Kind      NodePlanKind   `json:"kind"`
	PlannedAt time.Time      `json:"plannedAt"`
	Signature string         `json:"signature"`
	Target    string         `json:"target"`
}

// NodePlanAction defines model for NodePlan.Action.
type NodePlanAction string

// NodePlanKind defines model for NodePlan.Kind.
type NodePlanKind string

// NodeSnapshot defines model for NodeSnapshot.
type NodeSnapshot struct {
	Content *string `json:"content,omitempty"`
	Digest  *string `json:"digest,omitempty"`
	Exists  bool    `json:"exists"`
}

// PasswordPolicy The set-time password policy the server enforces, published so sign-up and password-change forms can render exactly the same requirements. The denylist itself is never exposed, only the fact that one is applied.
type PasswordPolicy struct {
	// ClassExemptLength Length at or above which a passphrase is exempt from the character-class rule.
	ClassExemptLength int `json:"classExemptLength"`

	// DenylistApplied Whether common and predictable passwords are rejected.
	DenylistApplied bool `json:"denylistApplied"`
	MaxLength       int  `json:"maxLength"`
	MinLength       int  `json:"minLength"`

	// RejectsUsername Whether a password containing the account's username is rejected.
	RejectsUsername bool `json:"rejectsUsername"`

	// RequiredClasses How many of lowercase, uppercase, digit and symbol a password must mix.
	RequiredClasses int `json:"requiredClasses"`
}

// PasswordResponse defines model for PasswordResponse.
type PasswordResponse struct {
	// Next Where the client should go next. `mfa_enrollment` is an offer, not a gate: the session is already authenticated and the client may skip it. `mfa_challenge` is mandatory for an account with a confirmed factor — the session stays unauthenticated until the challenge is answered. `authenticated` means no further step is needed.
	Next PasswordResponseNext `json:"next"`
	User User                 `json:"user"`
}

// PasswordResponseNext Where the client should go next. `mfa_enrollment` is an offer, not a gate: the session is already authenticated and the client may skip it. `mfa_challenge` is mandatory for an account with a confirmed factor — the session stays unauthenticated until the challenge is answered. `authenticated` means no further step is needed.
type PasswordResponseNext string

// PhpDirective defines model for PhpDirective.
type PhpDirective struct {
	// Access PHP ini access scope
	Access PhpDirectiveAccess `json:"access"`

	// Managed Whether nexa's managed drop-in (or, per-site, the .user.ini) currently overrides this directive
	Managed bool `json:"managed"`

	// Module The extension (module) that registers the directive; "core" for the engine itself
	Module string `json:"module"`

	// Name php.ini directive name, e.g. memory_limit
	Name string `json:"name"`

	// Value The effective value under the FPM SAPI (including any nexa-managed override)
	Value string `json:"value"`
}

// PhpDirectiveAccess PHP ini access scope
type PhpDirectiveAccess string

// PhpExtension defines model for PhpExtension.
type PhpExtension struct {
	Installed bool `json:"installed"`

	// Name Bare module suffix, e.g. redis
	Name string `json:"name"`

	// Package The apt package the suffix resolves to for this branch, e.g. php8.3-redis
	Package string `json:"package"`
}

// PodmanStatus defines model for PodmanStatus.
type PodmanStatus struct {
	Available bool    `json:"available"`
	Path      *string `json:"path,omitempty"`
	Version   *string `json:"version,omitempty"`
}

// ProbeChange defines model for ProbeChange.
type ProbeChange struct {
	Content *string `json:"content,omitempty"`
	Present bool    `json:"present"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Status  ReadinessStatus `json:"status"`
	Version string          `json:"version"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// RecoveryCode defines model for RecoveryCode.
type RecoveryCode = string

// Runtime defines model for Runtime.
type Runtime struct {
	Enabled       bool          `json:"enabled"`
	Engine        RuntimeEngine `json:"engine"`
	Installed     bool          `json:"installed"`
	SupportStatus string        `json:"supportStatus"`
	Version       string        `json:"version"`
}

// RuntimeEngine defines model for Runtime.Engine.
type RuntimeEngine string

// SavePhpSettings Directives to set to a value, and directives to reset to their default
type SavePhpSettings struct {
	Reset *[]string          `json:"reset,omitempty"`
	Set   *map[string]string `json:"set,omitempty"`

	// Version PHP branch to save (branch-wide settings only; omitted for per-site saves)
	Version *string `json:"version,omitempty"`
}

// ScheduleArtifact defines model for ScheduleArtifact.
type ScheduleArtifact struct {
	Content string `json:"content"`
	Group   string `json:"group"`
	Mode    int    `json:"mode"`
	Owner   string `json:"owner"`
	Path    string `json:"path"`
	Remove  bool   `json:"remove"`
}

// SchedulePlan defines model for SchedulePlan.
type SchedulePlan struct {
	Artifacts []ScheduleArtifact `json:"artifacts"`
	Before    []ScheduleSnapshot `json:"before"`
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        string             `json:"id"`
	Kind      SchedulePlanKind   `json:"kind"`
	PlannedAt time.Time          `json:"plannedAt"`
	Signature *string            `json:"signature,omitempty"`
	Task      SchedulePlanTask   `json:"task"`
	Warnings  []string           `json:"warnings"`
}

// SchedulePlanKind defines model for SchedulePlan.Kind.
type SchedulePlanKind string

// SchedulePlanTask defines model for SchedulePlanTask.
type SchedulePlanTask struct {
	Command        string    `json:"command"`
	CronExpression string    `json:"cronExpression"`
	Enabled        bool      `json:"enabled"`
	Id             string    `json:"id"`
	Name           string    `json:"name"`
	Scope          SiteScope `json:"scope"`
	TimeoutSeconds int       `json:"timeoutSeconds"`
}

// ScheduleRunRecord defines model for ScheduleRunRecord.
type ScheduleRunRecord struct {
	DurationSeconds int       `json:"durationSeconds"`
	ExitCode        int       `json:"exitCode"`
	StartedAt       time.Time `json:"startedAt"`
	Trigger         string    `json:"trigger"`
}

// ScheduleSnapshot defines model for ScheduleSnapshot.
type ScheduleSnapshot struct {
	Content *string `json:"content,omitempty"`
	Digest  *string `json:"digest,omitempty"`
	Exists  bool    `json:"exists"`
	Gid     *int    `json:"gid,omitempty"`
	Mode    *int    `json:"mode,omitempty"`
	Path    string  `json:"path"`
	Uid     *int    `json:"uid,omitempty"`
}

// ScheduledTask defines model for ScheduledTask.
type ScheduledTask struct {
	Command        string              `json:"command"`
	CreatedAt      time.Time           `json:"createdAt"`
	CronExpression string              `json:"cronExpression"`
	Enabled        bool                `json:"enabled"`
	Failure        *string             `json:"failure,omitempty"`
	Id             string              `json:"id"`
	LastJobId      *int64              `json:"lastJobId,omitempty"`
	Name           string              `json:"name"`
	PendingRemoval bool                `json:"pendingRemoval"`
	SiteId         string              `json:"siteId"`
	Status         ScheduledTaskStatus `json:"status"`
	TimeoutSeconds int                 `json:"timeoutSeconds"`
	UpdatedAt      time.Time           `json:"updatedAt"`
}

// ScheduledTaskStatus defines model for ScheduledTask.Status.
type ScheduledTaskStatus string

// ScheduledTaskRequest defines model for ScheduledTaskRequest.
type ScheduledTaskRequest struct {
	Command string `json:"command"`

	// CronExpression Exactly five numeric cron fields; names such as @daily or MON are rejected.
	CronExpression string `json:"cronExpression"`
	Enabled        *bool  `json:"enabled,omitempty"`
	Name           string `json:"name"`
	TimeoutSeconds int    `json:"timeoutSeconds"`
}

// SetDatabaseUserPassword defines model for SetDatabaseUserPassword.
type SetDatabaseUserPassword struct {
	Password string `json:"password"`
}

// SetDeploymentMode defines model for SetDeploymentMode.
type SetDeploymentMode struct {
	Mode SetDeploymentModeMode `json:"mode"`
}

// SetDeploymentModeMode defines model for SetDeploymentMode.Mode.
type SetDeploymentModeMode string

// SharedEnv The deployer layout's shared environment file. Its content is a secret in both directions - it is never logged, never audited, and never carried in a job payload.
type SharedEnv struct {
	Bytes      int        `json:"bytes"`
	Content    string     `json:"content"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	Path       string     `json:"path"`
	Present    bool       `json:"present"`
	Sha256     string     `json:"sha256"`
	SiteId     string     `json:"siteId"`
}

// Site defines model for Site.
type Site struct {
	CreatedAt time.Time `json:"createdAt"`

	// DeploymentMode Who owns the document root: the panel (standard) or a release tree the deployer publishes into (deployer). Always present on a site read.
	DeploymentMode SiteDeploymentMode `json:"deploymentMode"`
	DisplayName    string             `json:"displayName"`
	Failure        *string            `json:"failure,omitempty"`
	Id             string             `json:"id"`
	LastJobId      *int64             `json:"lastJobId,omitempty"`
	PhpVersion     string             `json:"phpVersion"`
	PrimaryDomain  string             `json:"primaryDomain"`
	RootPath       string             `json:"rootPath"`

	// Settings Per-site Nginx/PHP-FPM tuning. Every field is optional; an absent field falls back to a hardened default, so an empty object ({}) re-renders the baseline configuration identically.
	Settings   *SiteSettings `json:"settings,omitempty"`
	Slug       string        `json:"slug"`
	SocketPath string        `json:"socketPath"`
	Status     SiteStatus    `json:"status"`
	UnixUser   string        `json:"unixUser"`
	UpdatedAt  time.Time     `json:"updatedAt"`
}

// SiteDeploymentMode Who owns the document root: the panel (standard) or a release tree the deployer publishes into (deployer). Always present on a site read.
type SiteDeploymentMode string

// SiteStatus defines model for Site.Status.
type SiteStatus string

// SiteArtifact defines model for SiteArtifact.
type SiteArtifact struct {
	Content string           `json:"content"`
	Kind    SiteArtifactKind `json:"kind"`
	Mode    int              `json:"mode"`
	Path    string           `json:"path"`
}

// SiteArtifactKind defines model for SiteArtifact.Kind.
type SiteArtifactKind string

// SiteBasicAuth defines model for SiteBasicAuth.
type SiteBasicAuth struct {
	Enabled *bool `json:"enabled,omitempty"`

	// Password Plaintext password, hashed server-side. An empty value on save keeps the current password. Always empty on read.
	Password *string `json:"password,omitempty"`

	// Realm HTTP basic-auth realm. Absent or empty falls back to "Restricted".
	Realm    *string `json:"realm,omitempty"`
	Username *string `json:"username,omitempty"`
}

// SiteLogRotation Optional logrotate stanza for the site's own logs (logs/access.log, logs/error.log, logs/php-error.log). Absent or disabled emits no file at all, which is the historical behaviour: Nexa does not rotate site logs unless this is turned on.
type SiteLogRotation struct {
	// Enabled Write /etc/logrotate.d/nexa-<slug>. Disabling it stops the panel from managing the file on the next apply.
	Enabled *bool `json:"enabled,omitempty"`

	// Frequency Rotation interval. Absent or empty falls back to daily. `hourly` is only honoured if the node invokes logrotate hourly; the Debian/Ubuntu default logrotate.timer fires once a day, in which case an hourly stanza rotates at most once per day.
	Frequency *SiteLogRotationFrequency `json:"frequency,omitempty"`

	// KeepFiles Number of rotated copies to keep before the oldest is discarded (logrotate `rotate N`). 0 or absent falls back to 14.
	KeepFiles *int `json:"keepFiles,omitempty"`
}

// SiteLogRotationFrequency Rotation interval. Absent or empty falls back to daily. `hourly` is only honoured if the node invokes logrotate hourly; the Debian/Ubuntu default logrotate.timer fires once a day, in which case an hourly stanza rotates at most once per day.
type SiteLogRotationFrequency string

// SitePlan A signed node configuration plan. This endpoint is readable with sites.read, so basic-auth credential material is withheld from the response: the passwordHash field is empty and the password file's body, before-state, and digest read "[redacted]". Only the response is redacted — the stored plan keeps the real credential, which the node needs to re-render the file byte-identically when the plan is applied.
type SitePlan struct {
	Artifacts     []SiteArtifact           `json:"artifacts"`
	Before        []map[string]interface{} `json:"before"`
	EnabledBefore bool                     `json:"enabledBefore"`
	ExpiresAt     time.Time                `json:"expiresAt"`
	Id            string                   `json:"id"`
	Kind          SitePlanKind             `json:"kind"`
	PlannedAt     time.Time                `json:"plannedAt"`

	// Retired Managed paths this site must not have once the plan is applied — the conditional artifacts (rate-limit zone, htpasswd file, logrotate stanza) whose setting is currently off. The node re-derives this list from the plan's settings and refuses any path it would not itself have produced, so a plan can only ever delete files the operator owns for this site.
	Retired *[]string `json:"retired,omitempty"`

	// RetiredBefore Pre-apply snapshots of the retired paths, so a rollback can restore whatever the removal took away.
	RetiredBefore *[]map[string]interface{} `json:"retiredBefore,omitempty"`
	Signature     string                    `json:"signature"`
	Site          SitePlanTarget            `json:"site"`
	Warnings      []string                  `json:"warnings"`
}

// SitePlanKind defines model for SitePlan.Kind.
type SitePlanKind string

// SitePlanTarget defines model for SitePlanTarget.
type SitePlanTarget struct {
	Id            string       `json:"id"`
	PhpVersion    string       `json:"phpVersion"`
	PrimaryDomain string       `json:"primaryDomain"`
	RootPath      string       `json:"rootPath"`
	Routes        *[]SiteRoute `json:"routes,omitempty"`

	// Settings Per-site Nginx/PHP-FPM tuning. Every field is optional; an absent field falls back to a hardened default, so an empty object ({}) re-renders the baseline configuration identically.
	Settings   *SiteSettings `json:"settings,omitempty"`
	Slug       string        `json:"slug"`
	SocketPath string        `json:"socketPath"`
	Tls        *struct {
		CertificatePath *string `json:"certificatePath,omitempty"`
		PrivateKeyPath  *string `json:"privateKeyPath,omitempty"`
	} `json:"tls,omitempty"`
	TlsDomains *[]string `json:"tlsDomains,omitempty"`
	UnixUser   string    `json:"unixUser"`
}

// SiteRateLimit defines model for SiteRateLimit.
type SiteRateLimit struct {
	Burst             *int  `json:"burst,omitempty"`
	Enabled           *bool `json:"enabled,omitempty"`
	RequestsPerSecond *int  `json:"requestsPerSecond,omitempty"`
}

// SiteRoute defines model for SiteRoute.
type SiteRoute struct {
	Hostname       string        `json:"hostname"`
	Kind           SiteRouteKind `json:"kind"`
	RedirectTarget *string       `json:"redirectTarget,omitempty"`
}

// SiteRouteKind defines model for SiteRoute.Kind.
type SiteRouteKind string

// SiteScope defines model for SiteScope.
type SiteScope struct {
	RootPath string `json:"rootPath"`
	SiteId   string `json:"siteId"`
	Slug     string `json:"slug"`
	UnixUser string `json:"unixUser"`
}

// SiteSettings Per-site Nginx/PHP-FPM tuning. Every field is optional; an absent field falls back to a hardened default, so an empty object ({}) re-renders the baseline configuration identically.
type SiteSettings struct {
	// AccessLog Write the Nginx access log for this site. Absent defaults to on.
	AccessLog *bool          `json:"accessLog,omitempty"`
	BasicAuth *SiteBasicAuth `json:"basicAuth,omitempty"`

	// Charset Character set advertised by Nginx for this site. Absent or empty emits no `charset` directive at all, leaving the character set entirely to the application's own Content-Type header — that is the default and it is byte-identical to the configuration Nexa generated before this setting existed. An explicit `off` emits `charset off;`, which differs from absent only in that it also overrides a charset inherited from the server-wide http{} configuration. Values are lowercased server-side and must be one of the enumerated tokens; arbitrary charset names are rejected so the token can never escape the directive.
	Charset *SiteSettingsCharset `json:"charset,omitempty"`

	// ClientMaxBodyMb Nginx client_max_body_size in megabytes (note the lowercase 'b' in the key). Absent defaults to 64.
	ClientMaxBodyMb *int `json:"clientMaxBodyMb,omitempty"`

	// ErrorLog Write the Nginx error log for this site. Absent defaults to on.
	ErrorLog *bool `json:"errorLog,omitempty"`

	// Gzip Enable gzip response compression. Absent defaults to on.
	Gzip *bool `json:"gzip,omitempty"`

	// GzipLevel gzip compression level. 0 or absent falls back to 5.
	GzipLevel *int `json:"gzipLevel,omitempty"`

	// Hsts Emit an HTTP Strict-Transport-Security response header.
	Hsts *bool `json:"hsts,omitempty"`

	// HstsMaxAge HSTS max-age in seconds; only used when hsts is enabled. An explicit 0 (or absent) falls back to 15552000 (180 days).
	HstsMaxAge *int `json:"hstsMaxAge,omitempty"`

	// Http2 Enable HTTP/2. Absent defaults to on.
	Http2 *bool `json:"http2,omitempty"`

	// Http3 Enable HTTP/3 (QUIC). Absent or false defaults to off.
	Http3 *bool `json:"http3,omitempty"`

	// HttpsRedirect Redirect plain HTTP to HTTPS with a 301 on the port-80 server block. Absent defaults to true, which is the historical behaviour; an explicit false makes port 80 serve the site directly instead. The setting only has an effect once the site has a TLS certificate, and the ACME challenge location stays reachable over plain HTTP either way, so certificate issuance and renewal are unaffected. Note that an absent value and an explicit true render identically; OpenAPI cannot express that "absent means on" on a plain boolean, so it is documented here in prose (the same convention used for http2).
	HttpsRedirect *bool `json:"httpsRedirect,omitempty"`

	// IndexFiles Ordered list of application files Nginx tries when a directory is requested (the `index` directive). Absent or empty renders the baseline `index.php index.html`. Entries must be plain filenames — no directory separators, no traversal, no leading dot — and are emitted in exactly the order given, which is the order Nginx tries them. Duplicates are rejected. The first entry ending in `.php` also becomes the front controller that `location /` falls back to; when no entry ends in `.php` the fallback stays `index.php`.
	IndexFiles *[]string `json:"indexFiles,omitempty"`

	// LogRotation Optional logrotate stanza for the site's own logs (logs/access.log, logs/error.log, logs/php-error.log). Absent or disabled emits no file at all, which is the historical behaviour: Nexa does not rotate site logs unless this is turned on.
	LogRotation *SiteLogRotation `json:"logRotation,omitempty"`

	// PmMaxChildren PHP-FPM pm.max_children. 0 or absent falls back to 3.
	PmMaxChildren *int `json:"pmMaxChildren,omitempty"`

	// PmMaxRequests PHP-FPM pm.max_requests. Absent defaults to 500. An explicit 0 means unlimited, which differs from absent; OpenAPI cannot express that distinction on a plain integer, so it is documented here in prose.
	PmMaxRequests *int `json:"pmMaxRequests,omitempty"`

	// PmMode PHP-FPM process manager mode. Absent defaults to ondemand.
	PmMode    *SiteSettingsPmMode `json:"pmMode,omitempty"`
	RateLimit *SiteRateLimit      `json:"rateLimit,omitempty"`

	// StaticCacheDays Number of days to cache static assets via an expires header. Absent defaults to 30. An explicit 0 emits no expires header, which differs from absent; OpenAPI cannot express that distinction on a plain integer, so it is documented here in prose.
	StaticCacheDays *int `json:"staticCacheDays,omitempty"`

	// Subdirectory Document root to serve, relative to the site's public/ directory (for example `dist` or `app/public`). Absent or empty serves public/ itself. It is public-relative rather than site-root-relative on purpose: the site's logs/, private/, tmp/, and backups/ directories are siblings of public/, so a root-relative value could publish them. Traversal (`..`), absolute paths, and non-canonical values are rejected, and the directory is created on the node when the setting is applied.
	Subdirectory *string `json:"subdirectory,omitempty"`

	// WorkingDirectory PHP-FPM `chdir` for this site's worker processes, relative to the SITE ROOT (for example `public` or `app`). Absent or empty chdirs to the site root itself. This is a different axis from `subdirectory`, which is relative to public/ and selects the document root Nginx publishes: this setting publishes nothing, it only sets a worker's initial working directory, so it may legitimately name a directory outside public/. Traversal (`..`), absolute paths, and non-canonical values are rejected, and the directory is created on the node when the setting is applied. Depth is capped at 8 segments.
	WorkingDirectory *string `json:"workingDirectory,omitempty"`
}

// SiteSettingsCharset Character set advertised by Nginx for this site. Absent or empty emits no `charset` directive at all, leaving the character set entirely to the application's own Content-Type header — that is the default and it is byte-identical to the configuration Nexa generated before this setting existed. An explicit `off` emits `charset off;`, which differs from absent only in that it also overrides a charset inherited from the server-wide http{} configuration. Values are lowercased server-side and must be one of the enumerated tokens; arbitrary charset names are rejected so the token can never escape the directive.
type SiteSettingsCharset string

// SiteSettingsPmMode PHP-FPM process manager mode. Absent defaults to ondemand.
type SiteSettingsPmMode string

// SshAccess Interactive SSH access for one site, delivered through that site's Unix Owner. The key bodies are never returned; the fingerprint is the identity a human compares.
type SshAccess struct {
	// AuthorizedKeysPath The root-owned authorized-keys file the Match block names; it deliberately lives outside the site's home
	AuthorizedKeysPath string     `json:"authorizedKeysPath"`
	Enabled            bool       `json:"enabled"`
	EnabledAt          *time.Time `json:"enabledAt,omitempty"`
	Host               string     `json:"host"`
	Keys               []SshKey   `json:"keys"`
	Port               int        `json:"port"`

	// Shell The login shell the account currently has
	Shell  string `json:"shell"`
	SiteId string `json:"siteId"`

	// Username The site's Unix Owner, nexa_<slug>
	Username string `json:"username"`
}

// SshKey defines model for SshKey.
type SshKey struct {
	// Algorithm Key type as sshd names it, e.g. ssh-ed25519
	Algorithm string    `json:"algorithm"`
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"createdAt"`

	// Fingerprint SHA256 fingerprint, comparable against `ssh-keygen -lf`
	Fingerprint string `json:"fingerprint"`
	Id          string `json:"id"`
	Label       string `json:"label"`
}

// SystemOverview defines model for SystemOverview.
type SystemOverview struct {
	Memory     *MemorySnapshot `json:"memory,omitempty"`
	ObservedAt time.Time       `json:"observedAt"`
	Podman     PodmanStatus    `json:"podman"`
	Warnings   []string        `json:"warnings"`
}

// SystemRelease defines model for SystemRelease.
type SystemRelease struct {
	Notes       *string    `json:"notes,omitempty"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	Tag         string     `json:"tag"`
	Version     string     `json:"version"`
}

// SystemUpdateAvailability defines model for SystemUpdateAvailability.
type SystemUpdateAvailability struct {
	CheckedAt        time.Time      `json:"checkedAt"`
	InstalledVersion string         `json:"installedVersion"`
	Latest           *SystemRelease `json:"latest,omitempty"`
	UpdateAvailable  bool           `json:"updateAvailable"`
}

// TOTPCode defines model for TOTPCode.
type TOTPCode = string

// TestDeployKey defines model for TestDeployKey.
type TestDeployKey struct {
	Repository string `json:"repository"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	Password *string      `json:"password,omitempty"`
	Role     *ManagedRole `json:"role,omitempty"`
}

// User defines model for User.
type User struct {
	Id       string   `json:"id"`
	Role     UserRole `json:"role"`
	Username string   `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	User User `json:"user"`
}

// UserSiteGrants defines model for UserSiteGrants.
type UserSiteGrants struct {
	SiteIds []string `json:"siteIds"`
}

// WriteFile defines model for WriteFile.
type WriteFile struct {
	Content string `json:"content"`

	// ExpectedEtag Entity tag from the last read; an empty or missing value writes unconditionally.
	ExpectedEtag *string `json:"expectedEtag,omitempty"`
	Path         string  `json:"path"`
}

// WriteSharedEnv defines model for WriteSharedEnv.
type WriteSharedEnv struct {
	// Content The whole file; at most 65536 bytes
	Content string `json:"content"`
}

// JobID defines model for JobID.
type JobID = int64

// SiteID defines model for SiteID.
type SiteID = string

// TaskID defines model for TaskID.
type TaskID = string

// UploadID defines model for UploadID.
type UploadID = string

// ClientError Shared error envelope returned by every non-2xx JSON response.
type ClientError = Error

// ApplyAdminToolPlanParamsKind defines parameters for ApplyAdminToolPlan.
type ApplyAdminToolPlanParamsKind string

// CreateAdminToolLaunchJSONBody defines parameters for CreateAdminToolLaunch.
type CreateAdminToolLaunchJSONBody struct {
	AccountId    string                                    `json:"accountId"`
	DatabaseId   string                                    `json:"databaseId"`
	SourceEngine CreateAdminToolLaunchJSONBodySourceEngine `json:"sourceEngine"`
}

// CreateAdminToolLaunchParamsKind defines parameters for CreateAdminToolLaunch.
type CreateAdminToolLaunchParamsKind string

// CreateAdminToolLaunchJSONBodySourceEngine defines parameters for CreateAdminToolLaunch.
type CreateAdminToolLaunchJSONBodySourceEngine string

// GetAdminToolPlanParamsKind defines parameters for GetAdminToolPlan.
type GetAdminToolPlanParamsKind string

// PrepareAdminToolChangeJSONBody defines parameters for PrepareAdminToolChange.
type PrepareAdminToolChangeJSONBody struct {
	Action PrepareAdminToolChangeJSONBodyAction `json:"action"`
}

// PrepareAdminToolChangeParamsKind defines parameters for PrepareAdminToolChange.
type PrepareAdminToolChangeParamsKind string

// PrepareAdminToolChangeJSONBodyAction defines parameters for PrepareAdminToolChange.
type PrepareAdminToolChangeJSONBodyAction string

// PrepareApplicationChangeJSONBody defines parameters for PrepareApplicationChange.
type PrepareApplicationChangeJSONBody struct {
	Action PrepareApplicationChangeJSONBodyAction `json:"action"`
}

// PrepareApplicationChangeJSONBodyAction defines parameters for PrepareApplicationChange.
type PrepareApplicationChangeJSONBodyAction string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ConfirmMFAJSONBody defines parameters for ConfirmMFA.
type ConfirmMFAJSONBody struct {
	Code TOTPCode `json:"code"`
}

// RecoverMFAJSONBody defines parameters for RecoverMFA.
type RecoverMFAJSONBody struct {
	RecoveryCode RecoveryCode `json:"recoveryCode"`
}

// VerifyMFAJSONBody defines parameters for VerifyMFA.
type VerifyMFAJSONBody struct {
	union json.RawMessage
}

// VerifyMFAJSONBody0 defines parameters for VerifyMFA.
type VerifyMFAJSONBody0 struct {
	Code TOTPCode `json:"code"`
}

// VerifyMFAJSONBody1 defines parameters for VerifyMFA.
type VerifyMFAJSONBody1 struct {
	RecoveryCode RecoveryCode `json:"recoveryCode"`
}

// RestoreBackupCopyJSONBody defines parameters for RestoreBackupCopy.
type RestoreBackupCopyJSONBody struct {
	// AllowUnverified Explicit acknowledgement required when the copy has no passing integrity check.
	AllowUnverified bool `json:"allowUnverified"`

	// Databases Entries and destination database references must each be unique within the restore request.
	Databases []struct {
		Clear       bool   `json:"clear"`
		DatabaseRef string `json:"databaseRef"`
		Entry       string `json:"entry"`
	} `json:"databases"`

	// PreviewToken Short-lived actor- and plan-bound token returned by the restore preview endpoint.
	PreviewToken string `json:"previewToken"`

	// Sites Entries and destination site IDs must each be unique within the restore request.
	Sites []struct {
		Clear  bool   `json:"clear"`
		Entry  string `json:"entry"`
		SiteId string `json:"siteId"`
	} `json:"sites"`
}

// RestoreBackupCopyParams defines parameters for RestoreBackupCopy.
type RestoreBackupCopyParams struct {
	// IdempotencyKey Repeating the same key and request returns the original durable job. When omitted, the preview token supplies a safe default key.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// PreviewBackupRestoreJSONBody defines parameters for PreviewBackupRestore.
type PreviewBackupRestoreJSONBody struct {
	// AllowUnverified Explicit acknowledgement required when the copy has no passing integrity check.
	AllowUnverified bool `json:"allowUnverified"`
	Databases       []struct {
		Clear       bool   `json:"clear"`
		DatabaseRef string `json:"databaseRef"`
		Entry       string `json:"entry"`
	} `json:"databases"`
	Sites []struct {
		Clear  bool   `json:"clear"`
		Entry  string `json:"entry"`
		SiteId string `json:"siteId"`
	} `json:"sites"`
}

// PreviewBackupRestore200JSONResponseBodyIntegrityState defines parameters for PreviewBackupRestore.
type PreviewBackupRestore200JSONResponseBodyIntegrityState string

// PreviewBackupRestore200JSONResponseBodyItemsKind defines parameters for PreviewBackupRestore.
type PreviewBackupRestore200JSONResponseBodyItemsKind string

// RunBackupPlanParams defines parameters for RunBackupPlan.
type RunBackupPlanParams struct {
	// IdempotencyKey Repeating the same key and request returns the original durable job.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// RunSystemBackupJSONBody defines parameters for RunSystemBackup.
type RunSystemBackupJSONBody struct {
	// AccountId The storage account to upload the panel-state archive to.
	AccountId string `json:"accountId"`
}

// RunSystemBackupParams defines parameters for RunSystemBackup.
type RunSystemBackupParams struct {
	// IdempotencyKey Repeating the same key and request returns the original durable job.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	SiteId *string `form:"siteId,omitempty" json:"siteId,omitempty"`
}

// PrepareCertificateOperationJSONBody defines parameters for PrepareCertificateOperation.
type PrepareCertificateOperationJSONBody struct {
	Operation PrepareCertificateOperationJSONBodyOperation `json:"operation"`
}

// PrepareCertificateOperationJSONBodyOperation defines parameters for PrepareCertificateOperation.
type PrepareCertificateOperationJSONBodyOperation string

// ListManagedDatabasesParams defines parameters for ListManagedDatabases.
type ListManagedDatabasesParams struct {
	ServerId *string `form:"serverId,omitempty" json:"serverId,omitempty"`
}

// ListDatabaseGrantsParams defines parameters for ListDatabaseGrants.
type ListDatabaseGrantsParams struct {
	DatabaseId *string `form:"databaseId,omitempty" json:"databaseId,omitempty"`
}

// ListDatabaseRestorePointsParams defines parameters for ListDatabaseRestorePoints.
type ListDatabaseRestorePointsParams struct {
	DatabaseId *string `form:"databaseId,omitempty" json:"databaseId,omitempty"`
}

// ListDatabaseUsersParams defines parameters for ListDatabaseUsers.
type ListDatabaseUsersParams struct {
	ServerId *string `form:"serverId,omitempty" json:"serverId,omitempty"`
}

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	SiteId *string `form:"siteId,omitempty" json:"siteId,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitDiagnosticsJSONBody defines parameters for SubmitDiagnostics.
type SubmitDiagnosticsJSONBody struct {
	DelayMilliseconds *int `json:"delayMilliseconds,omitempty"`
}

// StreamJobEventsParams defines parameters for StreamJobEvents.
type StreamJobEventsParams struct {
	LastEventID *int `json:"Last-Event-ID,omitempty"`
}

// ListPhpExtensionsParams defines parameters for ListPhpExtensions.
type ListPhpExtensionsParams struct {
	Version string `form:"version" json:"version"`
}

// ListPhpSettingsParams defines parameters for ListPhpSettings.
type ListPhpSettingsParams struct {
	Version string `form:"version" json:"version"`
}

// ListSiteFilesParams defines parameters for ListSiteFiles.
type ListSiteFilesParams struct {
	// Path Site-relative directory; defaults to the site root.
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// ArchiveSiteFilesJSONBody defines parameters for ArchiveSiteFiles.
type ArchiveSiteFilesJSONBody struct {
	Paths  []string `json:"paths"`
	Target string   `json:"target"`
}

// ChmodSiteFileJSONBody defines parameters for ChmodSiteFile.
type ChmodSiteFileJSONBody struct {
	// Mode Three octal digits, such as "755".
	Mode string `json:"mode"`
	Path string `json:"path"`
}

// ReadSiteFileContentParams defines parameters for ReadSiteFileContent.
type ReadSiteFileContentParams struct {
	Path string `form:"path" json:"path"`
}

// CopySiteFileJSONBody defines parameters for CopySiteFile.
type CopySiteFileJSONBody struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// DeleteSiteFileJSONBody defines parameters for DeleteSiteFile.
type DeleteSiteFileJSONBody struct {
	Path      string `json:"path"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// DeleteSiteFile200JSONResponseBodyStatus defines parameters for DeleteSiteFile.
type DeleteSiteFile200JSONResponseBodyStatus string

// DownloadSiteFileParams defines parameters for DownloadSiteFile.
type DownloadSiteFileParams struct {
	Path string `form:"path" json:"path"`
}

// ExtractSiteArchiveJSONBody defines parameters for ExtractSiteArchive.
type ExtractSiteArchiveJSONBody struct {
	Path      string `json:"path"`
	TargetDir string `json:"targetDir"`
}

// CreateSiteDirectoryJSONBody defines parameters for CreateSiteDirectory.
type CreateSiteDirectoryJSONBody struct {
	Path string `json:"path"`
}

// MoveSiteFileJSONBody defines parameters for MoveSiteFile.
type MoveSiteFileJSONBody struct {
	From      string `json:"from"`
	Overwrite *bool  `json:"overwrite,omitempty"`
	To        string `json:"to"`
}

// MeasureSiteDirectorySizeJSONBody defines parameters for MeasureSiteDirectorySize.
type MeasureSiteDirectorySizeJSONBody struct {
	Path string `json:"path"`
}

// StatSiteFileParams defines parameters for StatSiteFile.
type StatSiteFileParams struct {
	Path string `form:"path" json:"path"`
}

// BeginSiteFileUploadJSONBody defines parameters for BeginSiteFileUpload.
type BeginSiteFileUploadJSONBody struct {
	Overwrite *bool  `json:"overwrite,omitempty"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
}

// AbortSiteFileUpload200JSONResponseBodyStatus defines parameters for AbortSiteFileUpload.
type AbortSiteFileUpload200JSONResponseBodyStatus string

// UploadSiteFileChunkParams defines parameters for UploadSiteFileChunk.
type UploadSiteFileChunkParams struct {
	// Offset Byte offset of this chunk within the staged file.
	Offset int64 `form:"offset" json:"offset"`
}

// UploadSiteFileChunk200JSONResponseBodyStatus defines parameters for UploadSiteFileChunk.
type UploadSiteFileChunk200JSONResponseBodyStatus string

// DownloadSiteLogParams defines parameters for DownloadSiteLog.
type DownloadSiteLogParams struct {
	Name string `form:"name" json:"name"`
}

// ReadSiteLogParams defines parameters for ReadSiteLog.
type ReadSiteLogParams struct {
	// Name Log file name slash-relative to the site logs directory.
	Name string `form:"name" json:"name"`

	// Tail Trailing lines to return in tail mode; values above the maximum are capped.
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`

	// Max Read window in bytes; values above the maximum are capped.
	Max *int `form:"max,omitempty" json:"max,omitempty"`

	// Offset Return complete lines appended since this byte offset instead of tailing.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`

	// Filter Case-insensitive substring filter applied per line.
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// StreamSiteLogParams defines parameters for StreamSiteLog.
type StreamSiteLogParams struct {
	Name   string  `form:"name" json:"name"`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`

	// LastEventID Resume the tail from this byte offset.
	LastEventID *int64 `json:"Last-Event-ID,omitempty"`
}

// StageSiteSftpCredentialsJSONBody defines parameters for StageSiteSftpCredentials.
type StageSiteSftpCredentialsJSONBody struct {
	Password string `json:"password"`
}

// CreateAdminToolLaunchJSONRequestBody defines body for CreateAdminToolLaunch for application/json ContentType.
type CreateAdminToolLaunchJSONRequestBody CreateAdminToolLaunchJSONBody

// PrepareAdminToolChangeJSONRequestBody defines body for PrepareAdminToolChange for application/json ContentType.
type PrepareAdminToolChangeJSONRequestBody PrepareAdminToolChangeJSONBody

// PrepareApplicationChangeJSONRequestBody defines body for PrepareApplicationChange for application/json ContentType.
type PrepareApplicationChangeJSONRequestBody PrepareApplicationChangeJSONBody

// BootstrapAdministratorJSONRequestBody defines body for BootstrapAdministrator for application/json ContentType.
type BootstrapAdministratorJSONRequestBody = BootstrapRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// ConfirmMFAJSONRequestBody defines body for ConfirmMFA for application/json ContentType.
type ConfirmMFAJSONRequestBody ConfirmMFAJSONBody

// DisableMFAJSONRequestBody defines body for DisableMFA for application/json ContentType.
type DisableMFAJSONRequestBody = MFADisableRequest

// RecoverMFAJSONRequestBody defines body for RecoverMFA for application/json ContentType.
type RecoverMFAJSONRequestBody RecoverMFAJSONBody

// VerifyMFAJSONRequestBody defines body for VerifyMFA for application/json ContentType.
type VerifyMFAJSONRequestBody VerifyMFAJSONBody

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RestoreBackupCopyJSONRequestBody defines body for RestoreBackupCopy for application/json ContentType.
type RestoreBackupCopyJSONRequestBody RestoreBackupCopyJSONBody

// PreviewBackupRestoreJSONRequestBody defines body for PreviewBackupRestore for application/json ContentType.
type PreviewBackupRestoreJSONRequestBody PreviewBackupRestoreJSONBody

// RunSystemBackupJSONRequestBody defines body for RunSystemBackup for application/json ContentType.
type RunSystemBackupJSONRequestBody RunSystemBackupJSONBody

// CreateCertificateJSONRequestBody defines body for CreateCertificate for application/json ContentType.
type CreateCertificateJSONRequestBody = CreateCertificate

// PrepareCertificateOperationJSONRequestBody defines body for PrepareCertificateOperation for application/json ContentType.
type PrepareCertificateOperationJSONRequestBody PrepareCertificateOperationJSONBody

// CreateManagedDatabaseJSONRequestBody defines body for CreateManagedDatabase for application/json ContentType.
type CreateManagedDatabaseJSONRequestBody = CreateManagedDatabase

// CreateDatabaseGrantJSONRequestBody defines body for CreateDatabaseGrant for application/json ContentType.
type CreateDatabaseGrantJSONRequestBody = CreateDatabaseGrant

// CreateDatabaseServerJSONRequestBody defines body for CreateDatabaseServer for application/json ContentType.
type CreateDatabaseServerJSONRequestBody = CreateDatabaseServer

// CreateDatabaseUserJSONRequestBody defines body for CreateDatabaseUser for application/json ContentType.
type CreateDatabaseUserJSONRequestBody = CreateDatabaseUser

// SetDatabaseUserPasswordJSONRequestBody defines body for SetDatabaseUserPassword for application/json ContentType.
type SetDatabaseUserPasswordJSONRequestBody = SetDatabaseUserPassword

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomain

// SubmitDiagnosticsJSONRequestBody defines body for SubmitDiagnostics for application/json ContentType.
type SubmitDiagnosticsJSONRequestBody SubmitDiagnosticsJSONBody

// ApplyManagedProbePlanJSONRequestBody defines body for ApplyManagedProbePlan for application/json ContentType.
type ApplyManagedProbePlanJSONRequestBody = NodePlan

// PlanManagedProbeJSONRequestBody defines body for PlanManagedProbe for application/json ContentType.
type PlanManagedProbeJSONRequestBody = ProbeChange

// RollbackManagedProbePlanJSONRequestBody defines body for RollbackManagedProbePlan for application/json ContentType.
type RollbackManagedProbePlanJSONRequestBody = NodePlan

// ChangePhpExtensionJSONRequestBody defines body for ChangePhpExtension for application/json ContentType.
type ChangePhpExtensionJSONRequestBody = ChangePhpExtension

// SavePhpSettingsJSONRequestBody defines body for SavePhpSettings for application/json ContentType.
type SavePhpSettingsJSONRequestBody = SavePhpSettings

// SaveSitePhpSettingsJSONRequestBody defines body for SaveSitePhpSettings for application/json ContentType.
type SaveSitePhpSettingsJSONRequestBody = SavePhpSettings

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSite

// EnsureSiteDeployKeyJSONRequestBody defines body for EnsureSiteDeployKey for application/json ContentType.
type EnsureSiteDeployKeyJSONRequestBody = EnsureDeployKey

// TestSiteDeployKeyJSONRequestBody defines body for TestSiteDeployKey for application/json ContentType.
type TestSiteDeployKeyJSONRequestBody = TestDeployKey

// SetSiteDeploymentModeJSONRequestBody defines body for SetSiteDeploymentMode for application/json ContentType.
type SetSiteDeploymentModeJSONRequestBody = SetDeploymentMode

// UpdateSiteSharedEnvJSONRequestBody defines body for UpdateSiteSharedEnv for application/json ContentType.
type UpdateSiteSharedEnvJSONRequestBody = WriteSharedEnv

// ArchiveSiteFilesJSONRequestBody defines body for ArchiveSiteFiles for application/json ContentType.
type ArchiveSiteFilesJSONRequestBody ArchiveSiteFilesJSONBody

// ChmodSiteFileJSONRequestBody defines body for ChmodSiteFile for application/json ContentType.
type ChmodSiteFileJSONRequestBody ChmodSiteFileJSONBody

// WriteSiteFileContentJSONRequestBody defines body for WriteSiteFileContent for application/json ContentType.
type WriteSiteFileContentJSONRequestBody = WriteFile

// CopySiteFileJSONRequestBody defines body for CopySiteFile for application/json ContentType.
type CopySiteFileJSONRequestBody CopySiteFileJSONBody

// DeleteSiteFileJSONRequestBody defines body for DeleteSiteFile for application/json ContentType.
type DeleteSiteFileJSONRequestBody DeleteSiteFileJSONBody

// ExtractSiteArchiveJSONRequestBody defines body for ExtractSiteArchive for application/json ContentType.
type ExtractSiteArchiveJSONRequestBody ExtractSiteArchiveJSONBody

// CreateSiteDirectoryJSONRequestBody defines body for CreateSiteDirectory for application/json ContentType.
type CreateSiteDirectoryJSONRequestBody CreateSiteDirectoryJSONBody

// MoveSiteFileJSONRequestBody defines body for MoveSiteFile for application/json ContentType.
type MoveSiteFileJSONRequestBody MoveSiteFileJSONBody

// MeasureSiteDirectorySizeJSONRequestBody defines body for MeasureSiteDirectorySize for application/json ContentType.
type MeasureSiteDirectorySizeJSONRequestBody MeasureSiteDirectorySizeJSONBody

// BeginSiteFileUploadJSONRequestBody defines body for BeginSiteFileUpload for application/json ContentType.
type BeginSiteFileUploadJSONRequestBody BeginSiteFileUploadJSONBody

// UpdateSiteSettingsJSONRequestBody defines body for UpdateSiteSettings for application/json ContentType.
type UpdateSiteSettingsJSONRequestBody = SiteSettings

// StageSiteSftpCredentialsJSONRequestBody defines body for StageSiteSftpCredentials for application/json ContentType.
type StageSiteSftpCredentialsJSONRequestBody StageSiteSftpCredentialsJSONBody

// AddSiteSshKeyJSONRequestBody defines body for AddSiteSshKey for application/json ContentType.
type AddSiteSshKeyJSONRequestBody = AddSshKey

// GenerateSiteSshKeyJSONRequestBody defines body for GenerateSiteSshKey for application/json ContentType.
type GenerateSiteSshKeyJSONRequestBody = GenerateSshKey

// CreateScheduledTaskJSONRequestBody defines body for CreateScheduledTask for application/json ContentType.
type CreateScheduledTaskJSONRequestBody = ScheduledTaskRequest

// UpdateScheduledTaskJSONRequestBody defines body for UpdateScheduledTask for application/json ContentType.
type UpdateScheduledTaskJSONRequestBody = ScheduledTaskRequest

// ApplySystemUpdateJSONRequestBody defines body for ApplySystemUpdate for application/json ContentType.
type ApplySystemUpdateJSONRequestBody = ApplySystemUpdate

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUser

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUser

// ReplaceUserSiteGrantsJSONRequestBody defines body for ReplaceUserSiteGrants for application/json ContentType.
type ReplaceUserSiteGrantsJSONRequestBody = UserSiteGrants

// AsVerifyMFAJSONBody0 returns the union data inside the VerifyMFAJSONBody as a VerifyMFAJSONBody0
func (t VerifyMFAJSONBody) AsVerifyMFAJSONBody0() (VerifyMFAJSONBody0, error) {
	var body VerifyMFAJSONBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyMFAJSONBody0 overwrites any union data inside the VerifyMFAJSONBody as the provided VerifyMFAJSONBody0
func (t *VerifyMFAJSONBody) FromVerifyMFAJSONBody0(v VerifyMFAJSONBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyMFAJSONBody0 performs a merge with any union data inside the VerifyMFAJSONBody, using the provided VerifyMFAJSONBody0
func (t *VerifyMFAJSONBody) MergeVerifyMFAJSONBody0(v VerifyMFAJSONBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVerifyMFAJSONBody1 returns the union data inside the VerifyMFAJSONBody as a VerifyMFAJSONBody1
func (t VerifyMFAJSONBody) AsVerifyMFAJSONBody1() (VerifyMFAJSONBody1, error) {
	var body VerifyMFAJSONBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyMFAJSONBody1 overwrites any union data inside the VerifyMFAJSONBody as the provided VerifyMFAJSONBody1
func (t *VerifyMFAJSONBody) FromVerifyMFAJSONBody1(v VerifyMFAJSONBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyMFAJSONBody1 performs a merge with any union data inside the VerifyMFAJSONBody, using the provided VerifyMFAJSONBody1
func (t *VerifyMFAJSONBody) MergeVerifyMFAJSONBody1(v VerifyMFAJSONBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifyMFAJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VerifyMFAJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
